# Netlify build configuration file

[build]
  # Ye command batayega ki deploy karte waqt kya karna hai
  command = "echo 'No build command needed'"

# Ye plugin humare environment variables ko inject karega
[[plugins]]
  package = "@netlify/plugin-contextual-env"

# Ye section humare placeholders ko actual values se replace karega
[context.production.environment]
  TELEGRAM_BOT_TOKEN = "8045449350:AAHQChcqTeTB3fcxE55kMMffKLUafSNVTG0"
  TELEGRAM_CHAT_ID = "7291244998"
